# Generated by Django 5.2.18 on 2026-10-07 10:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('project_type', models.CharField(max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(max_length=5000)),
                ('deadline', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouverte'), ('CLOSED', 'Clôturée'), ('CANCELLED', 'Annulée')], db_index=True, default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('deadline', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000)),
                ('similar_projects', models.JSONField(blank=True, default=list)),
                ('team_summary', models.CharField(blank=True, max_length=500)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Envoyée'), ('IN_REVIEW', 'En étude'), ('SHORTLISTED', 'Présélectionnée'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée'), ('WITHDRAWN', 'Retirée')], db_index=True, default='SUBMITTED', max_length=16)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='companies.companyprofile')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status', 'deadline', 'city'], name='opportuniti_status_d3a76e_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('budget_min__isnull', True), ('budget_max__isnull', True), ('budget_min__lte', models.F('budget_max')), _connector='OR'), name='opportunity_budget_min_lte_max'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['company', 'status', 'created_at'], name='opportuniti_company_60c5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['opportunity', 'status'], name='opportuniti_opportu_3d9fba_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('opportunity', 'company'), name='uniq_opportunity_company_application'),
        ),
    ]
