# Generated by Django 5.2.18 on 2026-10-07 10:35

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Client'), ('BTP_COMPANY', 'Entreprise BTP'), ('FIELD_AGENT', 'Agent terrain'), ('PROJECT_MANAGER', 'Chef de projet'), ('ADMIN', 'Administrateur'), ('SUPER_ADMIN', 'Super-administrateur')], max_length=24)),
                ('permission', models.CharField(choices=[('VIEW_PROJECT', 'Voir les projets'), ('CREATE_PROJECT', 'Créer des projets'), ('EDIT_PROJECT', 'Modifier des projets'), ('MANAGE_PROJECT', 'Gérer les projets'), ('UPLOAD_EVIDENCE', 'Ajouter des preuves terrain'), ('VALIDATE_EVIDENCE', 'Valider des preuves terrain'), ('VIEW_FINANCE', 'Voir les finances'), ('MANAGE_FINANCE', 'Gérer les finances'), ('CREATE_OPPORTUNITY', 'Créer des opportunités'), ('APPLY_OPPORTUNITY', 'Répondre aux opportunités'), ('MANAGE_COMPANY', 'Gérer un profil entreprise'), ('MANAGE_CATALOG', 'Gérer le catalogue BTP'), ('MANAGE_SUBSCRIPTION', 'Gérer les abonnements'), ('MANAGE_USERS', 'Gérer les utilisateurs'), ('MANAGE_SERVICE_REQUESTS', 'Gérer les demandes'), ('VIEW_AUDIT_LOGS', 'Consulter les journaux')], max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['role', 'enabled'], name='accounts_ro_role_09f2e4_idx')],
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='uniq_role_permission')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(db_index=True, max_length=16, unique=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Client'), ('BTP_COMPANY', 'Entreprise BTP'), ('FIELD_AGENT', 'Agent terrain'), ('PROJECT_MANAGER', 'Chef de projet'), ('ADMIN', 'Administrateur'), ('SUPER_ADMIN', 'Super-administrateur')], db_index=True, default='CUSTOMER', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx')],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
