# Generated by Django 5.2.18 on 2026-10-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_terms_accepted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolegrant',
            name='permission',
            field=models.CharField(choices=[('VIEW_PROJECT', 'Voir les projets'), ('CREATE_PROJECT', 'Créer des projets'), ('EDIT_PROJECT', 'Modifier des projets'), ('MANAGE_PROJECT', 'Gérer les projets'), ('UPLOAD_EVIDENCE', 'Ajouter des preuves terrain'), ('VALIDATE_EVIDENCE', 'Valider des preuves terrain'), ('VIEW_FINANCE', 'Voir les finances'), ('MANAGE_FINANCE', 'Gérer les finances'), ('CREATE_OPPORTUNITY', 'Créer des opportunités'), ('APPLY_OPPORTUNITY', 'Répondre aux opportunités'), ('MANAGE_COMPANY', 'Gérer un profil entreprise'), ('MANAGE_CATALOG', 'Gérer le catalogue BTP'), ('MANAGE_SUBSCRIPTION', 'Gérer les abonnements'), ('MANAGE_USERS', 'Gérer les utilisateurs'), ('MANAGE_SERVICE_REQUESTS', 'Gérer les demandes'), ('VIEW_AUDIT_LOGS', 'Consulter les journaux'), ('ASSIGN_FIELD_AGENT', 'Affecter des agents terrain'), ('CREATE_FIELD_MISSION', 'Créer des missions terrain'), ('VIEW_FIELD_REPORT', 'Consulter les rapports terrain'), ('REVIEW_FIELD_REPORT', 'Valider ou corriger les rapports terrain'), ('MANAGE_PROJECT_ISSUE', 'Gérer les problèmes de chantier'), ('VIEW_ASSIGNED_MISSION', 'Voir ses missions terrain'), ('EXECUTE_ASSIGNED_MISSION', 'Exécuter ses missions terrain'), ('SUBMIT_FIELD_REPORT', 'Soumettre un rapport terrain'), ('REPORT_PROJECT_ISSUE', 'Signaler un problème terrain')], max_length=40),
        ),
    ]
