# Generated by Django 5.2.18 on 2026-10-07 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PROJECT', 'Projet'), ('TASK', 'Tâche'), ('EVIDENCE', 'Preuve terrain'), ('PAYMENT', 'Paiement'), ('SUBSCRIPTION', 'Abonnement'), ('APPLICATION', 'Candidature'), ('OPPORTUNITY', 'Opportunité'), ('SECURITY', 'Sécurité'), ('GENERAL', 'Général')], db_index=True, default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=128, null=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'read_at', 'created_at'], name='notificatio_user_id_478247_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False)), fields=('user', 'dedupe_key'), name='uniq_notification_dedupe_key')],
            },
        ),
    ]
