# Generated by Django 5.2.18 on 2026-10-07 16:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('MATERIALS', 'Matériaux'), ('LABOUR', 'Main-d’œuvre'), ('EQUIPMENT', 'Équipement'), ('TRANSPORT', 'Transport'), ('ADMIN', 'Frais administratifs'), ('OTHER', 'Autre')], db_index=True, default='OTHER', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('spent_at', models.DateField()),
                ('status', models.CharField(choices=[('DECLARED', 'Déclarée'), ('VALIDATED', 'Justifiée'), ('REJECTED', 'Refusée')], db_index=True, default='DECLARED', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('receipt', models.FileField(blank=True, upload_to='expenses/receipts/%Y/%m/')),
                ('receipt_original_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-spent_at', '-id'),
                'indexes': [models.Index(fields=['project', 'spent_at'], name='projects_pr_project_95df41_idx'), models.Index(fields=['project', 'status'], name='projects_pr_project_b26b3c_idx')],
            },
        ),
    ]
