# Generated by Django 5.2.18 on 2026-10-08 01:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def copy_legacy_field_agents(apps, schema_editor):
    """Crée les affectations enrichies depuis Project.field_agents sans retirer ce lien."""
    Project = apps.get_model("projects", "Project")
    ProjectAssignment = apps.get_model("projects", "ProjectAssignment")
    User = apps.get_model("accounts", "User")
    field_agent_ids = set(User.objects.filter(role="FIELD_AGENT").values_list("id", flat=True))
    for project in Project.objects.prefetch_related("field_agents").all():
        for user in project.field_agents.all():
            if user.pk in field_agent_ids:
                ProjectAssignment.objects.get_or_create(
                    project_id=project.pk,
                    user_id=user.pk,
                    role="FIELD_AGENT",
                    defaults={"status": "ACTIVE"},
                )


def reverse_copy_legacy_field_agents(apps, schema_editor):
    # Migration additive : les données historiques ne doivent pas être supprimées au rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='client_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo')], db_index=True, default='PHOTO', max_length=12),
        ),
        migrations.AddField(
            model_name='evidence',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='video',
            field=models.FileField(blank=True, upload_to='evidence/video/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='image',
            field=models.ImageField(blank=True, upload_to='evidence/original/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='FieldMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('mission_type', models.CharField(choices=[('INSPECTION', 'Visite d’inspection'), ('PROGRESS_CHECK', 'Contrôle d’avancement'), ('QUALITY_CONTROL', 'Contrôle qualité'), ('ISSUE_FOLLOW_UP', 'Suivi de problème'), ('OTHER', 'Autre mission')], db_index=True, default='INSPECTION', max_length=24)),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('ACCEPTED', 'Acceptée'), ('IN_PROGRESS', 'En cours'), ('SUBMITTED', 'Rapport soumis'), ('UNDER_REVIEW', 'En revue'), ('APPROVED', 'Validée'), ('REVISION_REQUIRED', 'Correction demandée'), ('CANCELLED', 'Annulée')], db_index=True, default='PLANNED', max_length=24)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('instructions', models.TextField(blank=True)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('requires_geo_confirmation', models.BooleanField(default=False)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revision_reason', models.TextField(blank=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_missions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_field_missions', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_missions', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_missions', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_missions', to='projects.projecttask')),
            ],
            options={
                'ordering': ('scheduled_start', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='projects.fieldmission'),
        ),
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('checklist_results', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('UNDER_REVIEW', 'En revue'), ('APPROVED', 'Validé'), ('REVISION_REQUIRED', 'Correction demandée')], db_index=True, default='DRAFT', max_length=24)),
                ('review_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('client_reference', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_report', to='projects.fieldmission')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_field_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FIELD_AGENT', 'Agent terrain')], default='FIELD_AGENT', max_length=24)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Suspendue'), ('ENDED', 'Terminée')], db_index=True, default='ACTIVE', max_length=16)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(copy_legacy_field_agents, reverse_copy_legacy_field_agents),
        migrations.CreateModel(
            name='ProjectIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('CRITICAL', 'Critique')], db_index=True, default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En traitement'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Clos')], db_index=True, default='OPEN', max_length=16)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client_reference', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_issues', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.fieldmission')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_project_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='projects.projectissue'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['mission', 'created_at'], name='projects_ev_mission_6e57dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(condition=models.Q(('client_reference', ''), _negated=True), fields=('uploaded_by', 'client_reference'), name='uniq_evidence_client_reference'),
        ),
        migrations.AddIndex(
            model_name='fieldmission',
            index=models.Index(fields=['project', 'status', 'scheduled_start'], name='projects_fi_project_1673ce_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldmission',
            index=models.Index(fields=['assigned_to', 'status', 'scheduled_start'], name='projects_fi_assigne_c349ff_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldmission',
            index=models.Index(fields=['status', 'scheduled_start'], name='projects_fi_status_04f156_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldreport',
            index=models.Index(fields=['status', 'updated_at'], name='projects_fi_status_3e675a_idx'),
        ),
        migrations.AddConstraint(
            model_name='fieldreport',
            constraint=models.UniqueConstraint(condition=models.Q(('client_reference', ''), _negated=True), fields=('submitted_by', 'client_reference'), name='uniq_field_report_client_reference'),
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_39a89f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['user', 'status'], name='projects_pr_user_id_24967a_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.UniqueConstraint(fields=('project', 'user', 'role'), name='uniq_project_assignment_role'),
        ),
        migrations.AddIndex(
            model_name='projectissue',
            index=models.Index(fields=['project', 'status', 'priority'], name='projects_pr_project_f43fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectissue',
            index=models.Index(fields=['mission', 'status'], name='projects_pr_mission_68d074_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectissue',
            constraint=models.UniqueConstraint(condition=models.Q(('client_reference', ''), _negated=True), fields=('reported_by', 'client_reference'), name='uniq_project_issue_client_reference'),
        ),
    ]
