# Generated by Django 5.2.18 on 2026-10-07 10:35

import django.db.models.deletion
import django.utils.timezone
import service_requests.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(default=service_requests.models.generate_request_code, editable=False, max_length=24, unique=True)),
                ('service_type', models.CharField(choices=[('BUILD', 'Suivi de chantier'), ('TAKEOVER', 'Suivi d’un chantier existant'), ('MAINTENANCE', 'Entretien immobilier'), ('OTHER', 'Autre besoin')], db_index=True, max_length=20)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('phone', models.CharField(db_index=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('project_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('NEW', 'Nouvelle'), ('IN_REVIEW', 'En étude'), ('CONTACTED', 'Contactée'), ('CONVERTED', 'Projet créé'), ('CLOSED', 'Clôturée')], db_index=True, default='NEW', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service-requests/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service_requests.servicerequest')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'created_at'], name='service_req_status_0ae749_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['owner', 'created_at'], name='service_req_owner_i_fa52c1_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['service_type', 'status'], name='service_req_service_168b94_idx'),
        ),
    ]
