# Generated by Django 5.2.18 on 2026-10-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectexpense'),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='related_project',
            field=models.ForeignKey(blank=True, help_text='Projet déjà suivi par KEMTA auquel se rattache cette demande.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='projects.project'),
        ),
    ]
