# Generated by Django 5.2.18 on 2026-10-07 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('services', models.JSONField(blank=True, default=list)),
                ('intervention_areas', models.JSONField(blank=True, default=list)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('project_type', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='companies/portfolio/%Y/%m/')),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='companies.companyprofile')),
            ],
            options={
                'ordering': ('position', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['is_published', 'verified', 'city'], name='companies_c_is_publ_e4943b_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['company', 'is_published', 'position'], name='companies_p_company_82b42b_idx'),
        ),
    ]
